Apply pluginLoader, update peer deps, revert logic of npmignore
seznam/IMA.js-plugins pull request #66
Opened 2022-08-03 13:19 UTC by crysadrak

2022-08-05 09:47 UTC, jsimck requested changes

2022-08-05 09:47 UTC, jsimck commented on packages/plugin-analytic-fb-pixel/src/main.js
> +  $registerImaPlugin();
`$registerImaPlugin` can be deleted since it does not do anything in IMA 18.

2022-08-05 09:47 UTC, jsimck commented on packages/plugin-analytic-google/src/main.js
> +  $registerImaPlugin();
delete

2022-08-05 09:47 UTC, jsimck commented on packages/plugin-hot-reload/src/main.js
> +  $registerImaPlugin();
`delete`

2022-08-05 09:47 UTC, jsimck commented on packages/plugin-logger/src/main.js
> +  $registerImaPlugin(ns);
On other note, not sure if the ns definition is of any use.... but probably should be inlined, we don't want to have any references to `$registerImaPlugin` function in future versions as it is legacy and unused API.

2022-08-05 09:47 UTC, jsimck commented on packages/plugin-websocket/src/main.js
> +  $registerImaPlugin();
`delete`

2022-08-08 07:50 UTC, jsimck approved these changes

2022-08-12 10:07 UTC, Filipoliko commented on _templates/plugin/create/src/main.js.t
> +export { };
Do we still need to define the export since its empty?

2022-08-12 10:09 UTC, Filipoliko approved these changes

2022-08-12 11:31 UTC, merged